name: PR Check  #
on:
  pull_request:
    branches: [ "main" ]  # main 브랜치로의 PR에만 실행
    types: [opened, synchronize, reopened]  # PR이 열리거나, 업데이트되거나, 다시 열릴 때 실행

jobs:
  build:
    runs-on: ubuntu-latest  # Ubuntu 최신 버전에서 실행

    steps:
      - uses: actions/checkout@v4  # 코드 체크아웃

      - name: Set up JDK 17  # JDK 설정
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle  # Gradle 설정
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew  # gradlew 실행 권한 부여

      # 테스트 진행
      - name: Check with Gradle
        run: ./gradlew check  # 기본적인 검사 실행

      - name: Run tests
        run: ./gradlew test   # 단위 테스트 실행

      - name: Build with Gradle
        run: ./gradlew build  # 프로젝트 빌드